---

- name: Install alerta dependencies
  yum:
    name: '{{ alerta_depend_pkgs }}'
    state: present

- name: Install python3 virtualenv
  pip:
    name: virtualenv
    state: present
    executable: pip3

- name: Install alerta base packages using pip
  pip:
    name: '{{ alerta_pip_packages }}'
    virtualenv: '{{ alerta_base_dir }}'
    state: present
