---

- name: Install alerta dependencies
  yum:
    name: '{{ alerta_depend_pkgs }}'
    state: present

- name: Install python3 virtualenv
  pip:
    name: virtualenv
    state: present
    executable: pip3

- name: Install alerta server and alerta command-line tool
  pip:
    name: ['alerta', 'alerta-server', 'uwsgi']
    virtualenv: '{{ alerta_base_dir }}'
    state: present

- name: Create a wsgi python file
  copy:
    content: from alerta import app
    dest: '{{ alerta_base_dir }}/wsgi.py'

- name: Create alerta web console directory
  file:
    path: '{{ alerta_web_ui_dir }}'
    state: directory

- name: Get web console archive
  get_url:
    url: https://github.com/alerta/alerta-webui/releases/latest/download/alerta-webui.tar.gz
    dest: /tmp/alerta-webui.tar.gz

- name: Extract alerta web console
  unarchive:
    src: /tmp/alerta-webui.tar.gz
    dest: '{{ alerta_web_ui_dir }}'
    remote_src: true
    extra_opts: ['--strip-components=1']

- name: Configure alerta web console
  template:
    src: config.json.j2
    dest: '{{ alerta_web_ui_dir }}/config.json'

- name: Create uWsgi configuration file
  template:
    src: uwsgi.ini.j2
    dest: /etc/uwsgi.ini

- name: Configure alertad.conf
  template:
    src: alertad.conf.j2
    dest: /etc/alertad.conf
  notify: restart alerta

- name: Create a systemd configuration file for the alerta
  copy:
    src: alerta.service
    dest: /etc/systemd/system/alerta.service
  notify: restart alerta
